### ISSUE TITLE
Continuing training on a new data.

### ISSUE THREAD

**Issue by Aditi138** [Hyperparticle/udify#14]
I have a udify model on one dataset and I want to continue training on a new dataset. I used --resume option giving the serialization directory of the model trained on first dataset. However, that didn't work, even after first epoch the model seemed to have reset its parameters and started training from scratch. I also used a lower learning rate in the same config file but it didn't work. Is there anything I am doing wrong?

**Comment by Hyperparticle** [comment]
When using `--resume`, I believe the code uses the config files and weights inside the serialized directory. Make sure that the config inside points to your new dataset. Otherwise, you can also step through the code with a debugger to see why your weights aren't being loaded.

Hope that helps. Sorry for the late reply.
